<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>GT2Vol</RootNamespace>
    <AssemblyName>GTVolTool</AssemblyName>
    <RollForward>LatestMajor</RollForward>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="GT2K.cs" />
    <Compile Include="GT3Rebuild.cs" />
    <Compile Include="GT3Vol.cs" />
    <Compile Include="MemoryMappedFile.cs" />
    <Compile Include="Main.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Rebuild.cs" />
    <Compile Include="GT2VolFile.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
  </ItemGroup>

</Project>
